spring:
  application:
    name: spring-messaging
  datasource:
    url: jdbc:h2:mem:spring-messaging
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
